"""Encoder + admin cleanup tests.

These run real ffmpeg against tiny synthetic videos generated by ffmpeg's
lavfi testsrc. Each test takes well under a second.
"""
from __future__ import annotations

import os
import shutil
import subprocess
from pathlib import Path

import pytest
from fastapi.testclient import TestClient

from cuttlefish import db, scanner
from cuttlefish.server import create_app
from cuttlefish.workers import encoder

FFMPEG = shutil.which("ffmpeg")
ffmpeg_required = pytest.mark.skipif(FFMPEG is None, reason="ffmpeg not installed")


def _make_test_video(path: Path, duration: int = 1, size: str = "320x240") -> None:
    """Generate a tiny H.264 mp4 for the encoder to consume."""
    path.parent.mkdir(parents=True, exist_ok=True)
    cmd = [
        FFMPEG, "-y", "-loglevel", "error",
        "-f", "lavfi", "-i", f"testsrc=duration={duration}:size={size}:rate=10",
        "-f", "lavfi", "-i", f"sine=frequency=440:duration={duration}",
        "-c:v", "libx264", "-pix_fmt", "yuv420p",
        "-c:a", "aac", "-shortest", str(path),
    ]
    subprocess.run(cmd, check=True, capture_output=True)


def _populate(tmp_path: Path) -> tuple[Path, int]:
    """Build a movies library with one tiny video. Return (db_path, media_id)."""
    root = tmp_path / "movies"
    root.mkdir()
    _make_test_video(root / "Tiny Movie.mp4")
    # Sidecar files the encoder should pick up
    (root / "Tiny Movie.srt").write_text("1\n00:00:00,000 --> 00:00:01,000\nhi\n")
    (root / "Tiny Movie.jpg").write_bytes(b"\xff\xd8\xff\xe0")  # JPEG magic
    db_path = tmp_path / "test.db"
    conn = db.connect(db_path)
    db.init_schema(conn)
    with conn:
        cur = conn.execute(
            "INSERT INTO libraries (name, root_path) VALUES (?, ?)",
            ("movies", str(root)),
        )
        lib_id = cur.lastrowid
    scanner.scan_library(conn, lib_id, root)
    media_id = conn.execute(
        "SELECT id FROM media WHERE library_id = ?", (lib_id,)
    ).fetchone()["id"]
    return db_path, media_id


# --- helpers --------------------------------------------------------------


def test_safe_dirname():
    assert encoder.safe_dirname("Big Buck Bunny") == "Big Buck Bunny"
    assert encoder.safe_dirname("Foo/Bar:Baz") == "Foo_Bar_Baz"
    assert encoder.safe_dirname("...") == "untitled"
    assert encoder.safe_dirname("") == "untitled"


# --- core encode flow ----------------------------------------------------


@ffmpeg_required
def test_encode_creates_clean_layout_with_sidecars(tmp_path: Path):
    db_path, media_id = _populate(tmp_path)
    conn = db.connect(db_path)
    result = encoder.encode_media(conn, media_id, ffmpeg=FFMPEG)

    assert result.video_path.is_file()
    assert result.video_path.stat().st_size > 0
    assert result.video_path.name == "Tiny Movie.mp4"
    assert result.clean_dir.name == "Tiny Movie"
    assert result.poster_path is not None and result.poster_path.is_file()
    assert result.poster_path.name == "Tiny Movie.jpg"
    assert result.subtitle_path is not None and result.subtitle_path.is_file()
    assert result.subtitle_path.name == "Tiny Movie.srt"

    # Original is untouched
    original = tmp_path / "movies" / "Tiny Movie.mp4"
    assert original.is_file()

    # encoded_files row
    row = conn.execute(
        "SELECT video_path, subtitle_path, poster_path, size_bytes "
        "FROM encoded_files WHERE media_id = ?",
        (media_id,),
    ).fetchone()
    assert row["video_path"] == str(result.video_path)
    assert row["size_bytes"] > 0


@ffmpeg_required
def test_encode_refuses_to_overwrite_by_default(tmp_path: Path):
    db_path, media_id = _populate(tmp_path)
    conn = db.connect(db_path)
    encoder.encode_media(conn, media_id, ffmpeg=FFMPEG)
    with pytest.raises(encoder.EncodeError, match="already exists"):
        encoder.encode_media(conn, media_id, ffmpeg=FFMPEG)


def test_encode_unknown_media_raises(tmp_path: Path):
    db_path, _ = _populate(tmp_path)
    conn = db.connect(db_path)
    with pytest.raises(encoder.EncodeError, match="not found"):
        encoder.encode_media(conn, 99999, ffmpeg=FFMPEG or "ffmpeg")


# --- job queue ------------------------------------------------------------


def test_enqueue_and_claim_job(tmp_path: Path):
    db_path, media_id = _populate(tmp_path)
    conn = db.connect(db_path)
    job_id = encoder.enqueue_encode(conn, media_id)
    assert job_id > 0

    job = encoder.claim_next_job(conn, "encode")
    assert job is not None
    assert job["id"] == job_id
    assert job["media_id"] == media_id

    # Already claimed; next claim is empty.
    assert encoder.claim_next_job(conn, "encode") is None


def test_mark_done_and_failed(tmp_path: Path):
    db_path, media_id = _populate(tmp_path)
    conn = db.connect(db_path)
    j1 = encoder.enqueue_encode(conn, media_id)
    j2 = encoder.enqueue_encode(conn, media_id)
    encoder.claim_next_job(conn, "encode")
    encoder.mark_done(conn, j1, {"ok": True})
    encoder.claim_next_job(conn, "encode")
    encoder.mark_failed(conn, j2, "boom")
    rows = {r["id"]: dict(r) for r in conn.execute("SELECT id, status FROM jobs").fetchall()}
    assert rows[j1]["status"] == "done"
    assert rows[j2]["status"] == "failed"


@ffmpeg_required
def test_run_worker_once_processes_one_job(tmp_path: Path):
    db_path, media_id = _populate(tmp_path)
    conn = db.connect(db_path)
    encoder.enqueue_encode(conn, media_id)
    n = encoder.run_worker(db_path=db_path, once=True, ffmpeg=FFMPEG)
    assert n == 1
    job = conn.execute("SELECT status FROM jobs WHERE media_id = ?", (media_id,)).fetchone()
    assert job["status"] == "done"


@ffmpeg_required
def test_run_worker_once_no_jobs_returns_zero(tmp_path: Path):
    db_path, _ = _populate(tmp_path)
    n = encoder.run_worker(db_path=db_path, once=True, ffmpeg=FFMPEG)
    assert n == 0


# --- admin endpoints ------------------------------------------------------


@pytest.fixture
def admin_client(tmp_path: Path):
    db_path, media_id = _populate(tmp_path)
    app = create_app(db_path=db_path)
    client = TestClient(app)
    client.post("/api/auth/register", data={"username": "admin", "password": "secret123"})
    client.post("/api/auth/login", data={"username": "admin", "password": "secret123"})
    return client, db_path, media_id


def test_admin_endpoints_require_admin(tmp_path: Path):
    db_path, media_id = _populate(tmp_path)
    client = TestClient(create_app(db_path=db_path))
    # Anonymous
    assert client.post(f"/api/admin/encode/{media_id}").status_code == 401
    assert client.get("/api/admin/jobs").status_code == 401
    assert client.get("/api/admin/cleanup-candidates").status_code == 401
    # Logged in but not admin
    client.post("/api/auth/register", data={"username": "alice", "password": "secret123"})
    client.post("/api/auth/login", data={"username": "alice", "password": "secret123"})
    # alice IS admin (first user). Make a non-admin too.
    client.post("/api/auth/register", data={"username": "bob", "password": "secret123"})
    client.post("/api/auth/logout")
    client.post("/api/auth/login", data={"username": "bob", "password": "secret123"})
    assert client.post(f"/api/admin/encode/{media_id}").status_code == 403


def test_admin_enqueue_encode(admin_client):
    client, db_path, media_id = admin_client
    r = client.post(f"/api/admin/encode/{media_id}")
    assert r.status_code == 200
    assert r.json()["ok"] is True
    jobs = client.get("/api/admin/jobs").json()
    assert any(j["media_id"] == media_id and j["status"] == "queued" for j in jobs)


def test_admin_enqueue_unknown_media_404(admin_client):
    client, _, _ = admin_client
    assert client.post("/api/admin/encode/99999").status_code == 404


@ffmpeg_required
def test_cleanup_candidates_after_encode(admin_client):
    client, db_path, media_id = admin_client
    conn = db.connect(db_path)
    encoder.encode_media(conn, media_id, ffmpeg=FFMPEG)
    candidates = client.get("/api/admin/cleanup-candidates").json()
    assert len(candidates) == 1
    c = candidates[0]
    assert c["id"] == media_id
    assert c["original_path"].endswith("Tiny Movie.mp4")
    assert "Tiny Movie/Tiny Movie.mp4" in c["encoded_path"]
    assert c["original_size_bytes"] > 0


@ffmpeg_required
def test_delete_original_only_after_encode(admin_client):
    client, db_path, media_id = admin_client
    # Refusing without an encoded version
    r = client.delete(f"/api/admin/originals/{media_id}")
    assert r.status_code == 404

    conn = db.connect(db_path)
    encoder.encode_media(conn, media_id, ffmpeg=FFMPEG)
    original = Path(conn.execute(
        "SELECT source_path FROM media WHERE id = ?", (media_id,)
    ).fetchone()["source_path"])
    assert original.is_file()

    r = client.delete(f"/api/admin/originals/{media_id}")
    assert r.status_code == 200
    assert not original.exists()
    # Subsequent calls 404 because original is gone
    assert client.delete(f"/api/admin/originals/{media_id}").status_code == 404
